### ISSUE TITLE
Seeddms V6

### ISSUE THREAD

**Issue by Eweol** [nlippke/seeddms-docker#1]
Hi,
first of all nice work thank you.
I tried seeddms with original docker image first time and found your one later by searching an OCR option.
now is the question if I can change from V6 db to V5 db without reuploading all files!
Or if you are working on a docker image which supports V6 db from seeddms.

best regards

Eweol

**Comment by nlippke** [comment]
I am not sure whether you can easily downgrade to v5 due to database schema changes. Currently I am not migrating to v6 (no need). But it shouldn't be too hard to create a v6 version. Maybe you could try that be yourself?

**Comment by Eweol** [comment]
Hi @nlippke,
yeah thank you I tried it and it was very easy for me to migrate within the dockerfile.
Thank you
