### ISSUE TITLE
Request: LDAP

### ISSUE THREAD

**Issue by fcc48** [nlippke/seeddms-docker#3]
I have a request if you could add LDAP support to your Dockerimage?

I am not an expert, but i think the info here is helping with that?

https://stackoverflow.com/questions/67139850/installing-enabling-php-ldap-on-debian-linux-server-for-apache2

Thanks for considering.

**Comment by nlippke** [comment]
Shouldn't be a hard thing to do. But afterwards you still need to configure a connector manually in settings.xml in order to login via LDAP.

**Comment by nlippke** [comment]
LDAP support has been added. Check latest version 6.0.23.

**Comment by fcc48** [comment]
Thank you very much!!
Will check it out ASAP ;)

**Comment by fcc48** [comment]
Quick Feedback: I fully migrated to your image. LDAP is working well! Thank you very much!!
